### ISSUE TITLE
嗯.......似乎不能用了

### ISSUE THREAD

**Issue by bennylii** [nfer/ZhihuPrintMode#2]
某代码渣弱弱地求更新。。。。
主要是在新版的回答页面中失效了
![2017-02-07 21_43_20-.jpg](https://ooo.0o0.ooo/2017/02/07/5899cf36073f6.jpg)
右键无反应
//---------------------------------------------------------------------------------------------------------
还有一个问题，就是知乎现在拥有了防复制系统。。。。。目前可以禁止JS来关闭

**Comment by bennylii** [comment]
右键按完没反应。。。。

**Comment by nfer** [comment]
新版页面已支持

**Comment by bennylii** [comment]
棒!



Nfer Zhuang <notifications@github.com> 于 2018年7月31日周二 上午11:23写道：
